# Generated by Django 5.0.3 on 2024-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainlib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='temps',
            field=models.CharField(max_length=32),
        ),
    ]
